### ISSUE TITLE
platform is a bad name 

### ISSUE THREAD

**Issue by stashkov** [olehermanse/mrpg#1]
Hi! 

just FYI,

on mac os if you use python virtual env you will get a name conflict as described here
https://stackoverflow.com/questions/31111493/python-virtualenv-does-not-find-mac-ver-attribute-when-setup-a-new-env-suddenl

```
osx_version = platform.mac_ver()[0].split(".")
AttributeError: module 'platform' has no attribute 'mac_ver'
```

It can be solved by renaming platform folder

**Comment by olehermanse** [comment]
@stashkov Thanks! Please be aware that this is not ready to be tested ;)

**Comment by olehermanse** [comment]
This was fixed in: https://github.com/olehermanse/mrpg/commit/2f138ba8c770ca22e5107abffb168feec134ca9f
